# Generated by Django 4.1.3 on 2022-11-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(max_length=200, verbose_name='tipoDocumento')),
                ('numeroDocumento', models.CharField(max_length=200, verbose_name='numeroDocumento')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='apellido')),
                ('profesion', models.CharField(max_length=200, verbose_name='profesion')),
                ('edad', models.IntegerField(max_length=200, verbose_name='edad')),
                ('ciudad', models.CharField(max_length=200, verbose_name='ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=200)),
                ('puntosHojaVida', models.IntegerField(max_length=200)),
                ('puntosExperiencia', models.IntegerField(max_length=200)),
                ('puntosPostgrados', models.IntegerField(max_length=200)),
                ('puntosCertificaciones', models.IntegerField(max_length=200)),
                ('puntosIngles', models.IntegerField(max_length=200)),
                ('totalPuntos', models.IntegerField(max_length=200)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.aspirante')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.cargo')),
                ('estadoadmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.estadoadmision')),
            ],
        ),
    ]
