# Generated by Django 4.1.3 on 2022-11-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='edad',
            field=models.IntegerField(verbose_name='edad'),
        ),
    ]
